version: 2
updates:
  - package-ecosystem: "pip"
    directory: "requirements/base_requirements.txt"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "requirements/development_requirements.txt"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "requirements/heroku_requirements.txt"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "requirements/test_requirements.txt"
    schedule:
      interval: "daily"