version: '2.0'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
  koalixcrm:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=projectsettings.settings.development_settings
      - JAVA_HOME=/usr/bin/jdk1.8.0_162/jre
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8000:8000"
    depends_on:
      - db
